name=PicoWatch
version=1.4.15
author=SQFMI, UniqueDroid
maintainer=UniqueDroid
sentence=PicoWatch - An Open Source E-Paper Watch, forked from SQFMI's Watchy
paragraph=This library contains drivers and code samples for PicoWatch
category=Other
url=https://github.com/UniqueDroid/PicoWatch
architectures=esp32
depends=Adafruit GFX Library,Arduino_JSON,DS3232RTC,NTPClient,Rtc_Pcf8563,GxEPD2,WiFiManager
